services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: library
    ports:
      - '5433:5432'

  app:
    build: .
    environment:
      - MIGRATE_PATH=migrations
      - DB_DSN=postgres://postgres:123@db:5432/library?sslmode=disable
    ports:
      - "8080:8080"
    volumes:
      - "./migrations:/root/migrations"
    depends_on:
      - db